version: "3"

services:
  backend:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: minesweeper
    restart: unless-stopped
    volumes:
     - .:/minesweeper
    ports:
     - 8000:8000
    env_file: ./src/.env
    depends_on:
     - database
  database:
    image: postgres:alpine
    container_name: minesweeper_database
    env_file: ./src/.env
    volumes:
     - database:/var/lib/postgresql/data
    ports:
     - 5432:5432

volumes:
 database:
